name: Bug report
description: File a bug
body:
  - type: checkboxes
    attributes:
      label: Checkboxes
      options:
        - label: I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
          required: true
        - label: I have not found similar issue or disscussion at GitHub.
          required: true
        - label: Reboot doesn't fix the problem.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System name and version
      placeholder: Debian 12
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
      placeholder: "3.12"
    validations:
      required: true

  - type: input
    attributes:
      label: calibre version
      placeholder: "6.29"
    validations:
      required: true

  - type: input
    attributes:
      label: WordDumb plugin version
      placeholder: "3.29.7"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error message
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Plugin settings and reproduce steps
      placeholder: |
        0. Enable the X feature
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Generated files, screenshots or videos
      description: Drag and drop generated Word Wise, X-Ray files. Or screenshots.
