name: Bug report
description: File a bug
body:
  - type: checkboxes
    attributes:
      label: Checkboxes
      options:
        - label: I have read the document at [xxyzz.github.io/WordDumb](https://xxyzz.github.io/WordDumb).
          required: true
        - label: I have not found similar issue or disscussion at GitHub.
          required: true
        - label: Reboot doesn't fix the problem.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: System Information
      placeholder: |
        OS: Arch Linux, x86_64
        calibre version: 5.40.0
        Python version: 3.10.4
        Plugin version: 3.19.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error message
      render: text
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduce steps
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Generated files, screenshots or videos
      description: Drag and drop generated Word Wise, X-Ray files. Or screenshots.
