name: Lint Code Base

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: psf/black@stable
      - run: |
          python -m pip install mypy
          mypy .
          mypy __main__.py
      - run: |
          python -m pip install ruff
          ruff .
      - uses: crate-ci/typos@v1.16.15
