name: Lint Code Base

on:
  push:
    branches:
      - '**'
    paths:
      - '**.py'
  pull_request:
    branches:
      - '**'
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
