on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          branch: master
          workflow: tests.yml
          skip_unpack: true
          commit: ${{ github.sha }}

      - name: Rename zip file
        run: mv worddumb-*.zip worddumb-${GITHUB_REF_NAME}.zip

      - uses: softprops/action-gh-release@v1
        with:
          files: worddumb-*.zip
