on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tag name
        run: echo "FILENAME=worddumb-${GITHUB_REF##*/}.zip" >> $GITHUB_ENV

      - name: Build plugin
        run: |
          ./data/dump_lemmas.sh
          zip -r ${FILENAME} * -x@exclude.lst

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: worddumb-*.zip
