on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get tag name
        run: echo "FILENAME=worddumb-${GITHUB_REF##*/}.zip" >> $GITHUB_ENV

      - name: Install calibre
        run: |
          sudo apt install libegl1 libopengl0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Build plugin
        run: |
          bash -e ./build_plugin.sh
          zip -r ${FILENAME} * -x@exclude.lst

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: worddumb-*.zip
