name: Tests

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'klld/**'
      - 'translations/**'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'klld/**'
      - 'translations/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Install calibre on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libegl1 libopengl0
          sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install calibre on macOS
        if: matrix.os == 'macos-latest'
        run: |
          wget -nv -O calibre.dmg https://calibre-ebook.com/dist/osx
          hdiutil attach calibre.dmg
          cp -R /Volumes/calibre-*/calibre.app /Applications
          hdiutil unmount /Volumes/calibre-*
          rm calibre.dmg
          echo /Applications/calibre.app/Contents/MacOS >> $GITHUB_PATH

      - name: Install calibre and wget on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          choco install wget
          wget -nv -O calibre.msi https://calibre-ebook.com/dist/win64
          start /wait msiexec.exe /i calibre.msi /quiet
          del calibre.msi

      - name: Add calibre directory to Windows PATH
        if: matrix.os == 'windows-latest'
        run: echo "/C/Program Files/Calibre2" >> $GITHUB_PATH

      - name: Install KFX Input plugin
        run: |
          wget -nv -O KFX_Input.zip "https://www.mobileread.com/forums/attachment.php?attachmentid=194039&d=1653920104"
          calibre-customize -a KFX_Input.zip
          rm KFX_Input.zip

      - name: Download books
        run: |
          wget -nv https://github.com/xxyzz/WordDumb/files/8831564/books.zip
          unzip books.zip

      - name: Add books to library
        run: |
          mkdir ~/Calibre\ Library
          calibredb add -m ignore --with-library ~/Calibre\ Library *.kfx *.azw3 *.epub
          rm *.kfx *.azw3 *.epub books.zip

      - name: Build plugin(Unix)
        if: matrix.os != 'windows-latest'
        run: |
          bash -e ./build_plugin.sh
          zip -r worddumb-${{ github.sha }}.zip * -x@exclude.lst

      - name: Build plugin(Windows)
        if: matrix.os == 'windows-latest'
        run: |
          bash -e ./build_plugin.sh
          7z a -x@exclude.lst -x!.* -tzip worddumb-${{ github.sha }}.zip

      - name: Add plugin
        run: |
          calibre-customize -a worddumb-${{ github.sha }}.zip
          rm worddumb-${{ github.sha }}.zip

      - name: Get calibre python version
        if: matrix.os != 'macos-latest'
        run: echo "CALIBRE_PY=$(calibre-debug -c 'import platform; print(".".join(platform.python_version_tuple()[:2]))')" >> $GITHUB_ENV

      - name: Get macOS python version
        if: matrix.os == 'macos-latest'
        run: echo "MACOS_PY=$(python3 -c 'import platform; print(".".join(platform.python_version_tuple()[:2]))')" >> $GITHUB_ENV

      - name: Restore dependencies and Wikipedia cache(Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/cache@v3
        with:
          path: |
            ~/.config/calibre/plugins/worddumb-*
          key: ${{ runner.os }}-${{ hashFiles('data/x_ray_deps.json') }}-${{ env.CALIBRE_PY }}

      - name: Restore dependencies and Wikipedia cache(macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Preferences/calibre/plugins/worddumb-*
          key: ${{ runner.os }}-${{ hashFiles('data/x_ray_deps.json') }}-${{ hashFiles('data/extra_deps.json') }}-${{ env.MACOS_PY }}

      - name: Restore dependencies and Wikipedia cache(Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Roaming/calibre/plugins/worddumb-*
          key: ${{ runner.os }}-${{ hashFiles('data/x_ray_deps.json') }}-${{ env.CALIBRE_PY }}

      - name: Run test
        run: cd tests && calibre-debug test.py
        env:
          PYTHONWARNINGS: default
          CALIBRE_SHOW_DEPRECATION_WARNINGS: 1

      - name: Upload plugin
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: worddumb-${{ github.sha }}
          path: |
            .
            !.*
            !docs/*
            !tests/*
            !**/__pycache__/*
            !__pycache__/*
            !exclude.lst
            !klld/*
            !translations/*.po
            !Proficiency
